server:  port: 4050   

spring:  application:    name: payment-service
  config:    import: configserver:http://localhost:8888  datasource:    url: jdbc:mysql://localhost:3306/test    username: root      password: srivatsan    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:8761/eureka
  instance:    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} 
    prefer-ip-address: true        